// Station data for the 6 train, Pelham Bay Park -> Brooklyn Bridge-City Hall
// Order verified against the "6 (New York City Subway service)" route.
const Stations = {
  LINE_ID: "6",
  LINE_NAME: "Lexington Ave Local",
  LINE_COLOR: "#00933C",

  list: [
    "Pelham Bay Park",
    "Buhre Avenue",
    "Middletown Road",
    "Westchester Square–East Tremont Avenue",
    "Zerega Avenue",
    "Castle Hill Avenue",
    "Parkchester",
    "St. Lawrence Avenue",
    "Morrison Avenue–Soundview",
    "Elder Avenue",
    "Whitlock Avenue",
    "Hunts Point Avenue",
    "Longwood Avenue",
    "East 149th Street",
    "East 143rd Street–St. Mary's Street",
    "Cypress Avenue",
    "Brook Avenue",
    "Third Avenue–138th Street",
    "125th Street",
    "116th Street",
    "110th Street",
    "103rd Street",
    "96th Street",
    "86th Street",
    "77th Street",
    "68th Street–Hunter College",
    "59th Street",
    "51st Street",
    "Grand Central–42nd Street",
    "33rd Street",
    "28th Street",
    "23rd Street–Baruch College",
    "14th Street–Union Square",
    "Astor Place",
    "Bleecker Street",
    "Spring Street",
    "Canal Street",
    "Brooklyn Bridge–City Hall",
  ],
};
